transcend-io/terragrunt-atlantis-config

README.md, cmd/generate.go
Tested with and without the option `autoplan`
```
terragrunt-atlantis-config generate --autoplan --output ./output.tf
terragrunt-atlantis-config generate --output ./output.tf
```
=> Add option to enable auto plan

README.md, cmd/generate.go
Most commonly this will help out with repos that have a root-level parent `terragrunt.hcl` which doesn't actually provision anything itself.  In these cases we don't want to create a project in the `atlantis.yaml` because the plan will always be blank or error out.
We detect when a terragrunt.hcl file has an empty `terraform` block or an empty `terraform.source` parameter.  Also there's a command-line option to enable (default disabled)
=> Feature to ignore unplannable terragrunt.hcl files

cmd/generate.go, cmd/generate_test.go, cmd/golden/namedWorkflow.yaml, cmd/golden/settingRoot.yaml, cmd/golden/withAutoplan.yaml, cmd/golden/withoutParent.yaml
We had problematic cases in our monorepo where we had:
```
someDir:
| terragrunt.hcl
dirA:
| terragrunt.hcl (depends on ..)
dirB:
| terragrunt.hcl (depends on ..)
```
This was problematic because updating dirB would cause dirA to be included in the atlantis plan, because dirA depends on _any_ file in its parent directory, not just the terragrunt.hcl file it's meant to.
=> Add `/terragrunt.hcl` to the end of all dependency paths

Makefile, README.md, cmd/generate.go, cmd/golden/namedWorkflow.yaml, cmd/golden/settingRoot.yaml, cmd/golden/withAutoplan.yaml, cmd/golden/withoutParent.yaml, cmd/parse_locals.go, example-setup/extra_dependency/terragrunt.hcl, example-setup/test_file.json, go.mod, go.sum, main.go
For 99% of cases, this tool can sniff out all dependencies in a module. However, you may have times when you want to add in additional dependencies such as:
- You want to run _all_ modules any time your product has a major version bump
- You use Terragrunt's `read_terragrunt_config` function in your locals, and want to depend on the read file
- You believe a module should be reapplied any time some other file or directory is updated
In these cases, you can customize the `locals` block in that Terragrunt module to have a field named `extra_atlantis_dependencies` with a list
of values you want included in the config, such as:
```hcl
locals {
extra_atlantis_dependencies = [
"some_extra_dep",
find_in_parent_folders(".gitignore")
]
}
```
In your `atlantis.yaml` file, you will end up seeing …
=> Allow adding custom dependencies

.github/workflows/docker-build.yml, Dockerfile
Hello again!
I propose here a CI/CD change creating a container image pipeline.
To provide a binary package which is easy to consume in container-friendly environments.  For us, it's super handy to use with GitHub Actions because **skipping the build steps reduces run duration from ~2min to ~30s**.
1. Build container image (w/caching via BuildKit and Github Packages docker registry)
2. Tag container with PR ref (eg `pull-42-merge`)
3. Push container image to GitHub Packages to be use for further caching
1. Build container image (w/caching via BuildKit and Github Packages docker registry)
2. Tag container with `latest`
3. Push container image to GitHub Packages
1. Build container image (w/caching via BuildKit and Github Packages docker registry)
2. Tag container with git tag (eg `v0.6.1`) …
=> Feature: build container image and push to public repo

Dockerfile
Woops, the `COPY` line in the Dockerfile has an incorrect destination path. This explains why I keep having to override the `ENTRYPOINT` when running this container 🤦
=> Fix the copy-to dir in Dockerfile

Makefile, README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/withWorkspace.yaml
- _[none]_
Per the comments in the issue https://github.com/runatlantis/atlantis/issues/260 , atlantis locks the project based on the workspace name, parallel plan on different directories will fail with the error `the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again`.
This add an option to specify the workspace for each project with their path:
```
projects:
- autoplan:
enabled: false
when_modified:
- '*.hcl'
- '*.tf*'
- ./aws/prod/s3/terragrunt.hcl
- ./module/aws*.tf*
dir: aws/prod/s3
workflow: terragrunt
workspace: aws_prod_s3
```
- _[none]_
- _[none]_
=> Add option to specify workspace name

.gitignore, Makefile, README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/withProjectName.yaml, main.go
- _[none]_
As when defining different workspaces for each directory,
this info is also needed when running `atlantis plan/apply -d ${git_root}/stage/app -w stage_app`
to run the command on specific directory but one could also use the
`atlantis plan/apply -p stage_app` in case there is a project name defined.
As this uses the same convention with the name of workspace (which should
be unique) and the default value is disabled this should not create any
problems to the current users.
- _[none]_
- _[none]_
=> Support the addition of each Project Name in atlantis.yaml

cmd/generate.go, cmd/generate_test.go, cmd/golden/mergeParentDependencies.yaml, cmd/golden/parentAndChildDefinedWorkflow.yaml, cmd/golden/parentDefinedWorkflow.yaml, cmd/parse_locals.go, go.sum, test_examples/child_and_parent_specify_workflow/child/terragrunt.hcl, test_examples/child_and_parent_specify_workflow/terragrunt.hcl, test_examples/parent_with_extra_deps/child/terragrunt.hcl, test_examples/parent_with_extra_deps/terragrunt.hcl, test_examples/parent_with_workflow_local/child/terragrunt.hcl, test_examples/parent_with_workflow_local/terragrunt.hcl
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/59
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/46
There have been a few mentions in issues that people would prefer to not have to add `locals` to all their child terragrunt.hcl files, which makes sense. One way to make this more manageable is to allow specifying locals in parent files that get passed down to children.
This PR adds in that functionality:
- Workflow names will be prioritized by: child workflow local -> parent workflow local -> default from flag
- extra dependencies will be combined between parents and children
=> Inherit locals from parent terragrunt files

Makefile, README.md, main.go
Running a command like:
```bash
GOPRIVATE=github.com/transcend-io GO111MODULE=on go get github.com/transcend-io/terragrunt-atlantis-config@v0.9.0
terragrunt-atlantis-config version
```
would print out an empty version, because ldflags were not used during the build step of the install. While ldflags can be passed to `go get`, I think that having the version hardcoded into the application code such that the version will always display is a good idea.
=> Allow using hardcoded version as default

cmd/generate.go, cmd/golden/extraArguments.yaml, test_examples/extra_arguments/no_files_at_all/terragrunt.hcl, test_examples/extra_arguments/only_optional_files/terragrunt.hcl, test_examples/extra_arguments/only_required_files/terragrunt.hcl
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/66
Fixes issue where `extra_argument` blocks without required or optional fields specified caused a golang panic because of a segmentation fault when dereferencing a null pointer.
Relevant: https://www.youtube.com/watch?v=bLHL75H_VEM
=> Fix bug with parsing extra arguments

Makefile, README.md, cmd/generate.go, cmd/golden/extraArguments.yaml, main.go, test_examples/extra_arguments/var_file/terragrunt.hcl
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/60
Add support for `-var-file` extra_arguments in the `arguments` subfield.
=> Add support for `-var-file` extra_arguments

Makefile, README.md, cmd/generate.go, cmd/golden/mergeParentDependencies.yaml, cmd/parse_locals.go, main.go, test_examples/parent_with_extra_deps/deep/child/terragrunt.hcl, test_examples/parent_with_extra_deps/deep/file_in_parent_of_child.json, test_examples/parent_with_extra_deps/parent/folder_under_parent/common_tags.hcl, test_examples/parent_with_extra_deps/parent/terragrunt.hcl, test_examples/parent_with_extra_deps/terragrunt.hcl
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/60#issuecomment-702076380
Updates the parsing of parent terragrunt modules so that they are evaluated from the point of view of the child directories.
Added more testing and updated the documentation.
=> Have parent dependencies be relative to the child

cmd/generate_test.go, cmd/golden/infrastructureLive.yaml, test_examples/terragrunt-infrastructure-live-example/README.md, test_examples/terragrunt-infrastructure-live-example/non-prod/account.hcl, test_examples/terragrunt-infrastructure-live-example/non-prod/us-east-1/qa/env.hcl, test_examples/terragrunt-infrastructure-live-example/non-prod/us-east-1/qa/mysql/terragrunt.hcl, test_examples/terragrunt-infrastructure-live-example/non-prod/us-east-1/qa/webserver-cluster/terragrunt.hcl, test_examples/terragrunt-infrastructure-live-example/non-prod/us-east-1/region.hcl, test_examples/terragrunt-infrastructure-live-example/non-prod/us-east-1/stage/env.hcl, test_examples/terragrunt-infrastructure-live-example/non-prod/us-east-1/stage/mysql/terragrunt.hcl, test_examples/terragrunt-infrastructure-live-example/non-prod/us-east-1/stage/webserver-cluster/terragrunt.hcl, test_examples/terragrunt-infrastructure-live-example/prod/account.hcl, test_examples/terragrunt-infrastructure-live-example/prod/us-east-1/prod/env.hcl, test_examples/terragrunt-infrastructure-live-example/prod/us-east-1/prod/mysql/terragrunt.hcl, test_examples/terragrunt-infrastructure-live-example/prod/us-east-1/prod/webserver-cluster/terragrunt.hcl, test_examples/terragrunt-infrastructure-live-example/prod/us-east-1/region.hcl, test_examples/terragrunt-infrastructure-live-example/terragrunt.hcl
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/48#issuecomment-706984851
Added infrastructure-live repo as a test case to confirm it works without code changes to this library. The only modification was the addition of:
```hcl
extra_atlantis_dependencies = [
find_in_parent_folders("account.hcl"),
find_in_parent_folders("region.hcl"),
find_in_parent_folders("env.hcl"),
]
```
in the locals of the top level terragrunt file.
=> added infrastructure live test

README.md, cmd/config.go, cmd/generate.go, cmd/generate_test.go, cmd/golden/oldWorkflowsPreserved.yaml
- Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/79
Allow preserving old workflows. This is a breaking change, but should not affect anyone who already uses this library, so it should be fairly safe to release.
=> Allow preserving old workflows

cmd/generate.go, cmd/generate_test.go, cmd/golden/autoplan.yaml, cmd/parse_locals.go, test_examples/autoplan/autoplan_false/terragrunt.hcl, test_examples/autoplan/autoplan_true/terragrunt.hcl, test_examples/autoplan/set_in_parent/terragrunt.hcl, test_examples/autoplan/terragrunt.hcl
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/84
enables setting `atlantis_autoplan` in any parent or child terragrunt file
=> enable atlantis_autoplan local

README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/skip.yaml, cmd/parse_locals.go, test_examples/skip/set_in_parent/terragrunt.hcl, test_examples/skip/skip_false/terragrunt.hcl, test_examples/skip/skip_true/terragrunt.hcl, test_examples/skip/terragrunt.hcl
Sometimes you don't want a certain Terragrunt module in your CI flow.
It may be because it prints out sensitive information, it is a demo, or it can/should only be run locally. In any case, you can add `atlantis_skip` to the `locals` values and remove it from the output.
=> Add support for `atlantis_skip` local

README.md, cmd/config.go, cmd/generate.go, cmd/generate_test.go, cmd/golden/terraform_version.yaml, cmd/parse_locals.go, test_examples/terraform_version/inherit_from_parent/terragrunt.hcl, test_examples/terraform_version/override_parent/terragrunt.hcl, test_examples/terraform_version/terragrunt.hcl, test_examples/terraform_version/use_flag_default/terragrunt.hcl
- Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/53
Allow specifying a terraform_version to use in the client-side atlantis.yaml file. You can also override this value on a module basis by using the `locals` value `atlantis_terraform_version`
=> Support custom terraform versions

README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/withAutomerge.yaml
- #97 
This Pull adds a boolean flag `--automerge` to control the setting in the `atlantis.yaml`
- _[none]_
- _[should work on all]_
=> Add flag to control repo automerge setting

Makefile, README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/chained_dependency.yaml, cmd/golden/chained_dependency_no_flag.yaml, main.go, test_examples/chained_dependencies/dependency/terragrunt.hcl, test_examples/chained_dependencies/depender/terragrunt.hcl, test_examples/chained_dependencies/depender_on_depender/nested/terragrunt.hcl, test_examples/chained_dependencies/depender_on_depender/terragrunt.hcl
- Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/82
Before this change, if we had the dependency tree of modules
A -> B -> C
And module C is updated, only module B knows that C was updated, but we really want module A to know that C was updated as well.
This PR will also state that module A depends on module C.
It can be optionally controlled by the flag `--cascade-dependencies`, which defaults to true.
=> Allow cascading dependencies

README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/terragrunt_dependency_ignored.yaml
- Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/101
Adds a `--ignore-dependency-blocks` flag that allows ignoring `dependency` and `dependencies` blocks
=> Allow ignoring dependency blocks

Makefile, README.md, cmd/config.go, cmd/generate.go, cmd/generate_test.go, cmd/golden/apply_overrides.yaml, cmd/golden/apply_overrides_flag.yaml, cmd/parse_locals.go, main.go, test_examples/apply_requirements_overrides/child_that_does_not_override/terragrunt.hcl, test_examples/apply_requirements_overrides/child_that_overrides/terragrunt.hcl, test_examples/apply_requirements_overrides/terragrunt.hcl
- Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/108
Adds support for using `apply_requirements` in the terragrunt config.
These can be set in three ways:
1. Using a flag
You can use `--apply-requirements` in your `generate` command to set defaults that will apply to all modules
2. Using a local in the parent config
You can set the local `atlantis_apply_requirements` in your parent config to override all modules that inherit from that parent. This config is **not** additive to the `--apply-requirements` flag, but overrides the array entirely
3. Using a local in the child config
You can set the local `atlantis_apply_requirements` in your child config to override the setting for a single module. This config is **not** additive to the `--apply-requirements` flag or …
=> Add support for changing the `apply_requirements` field

cmd/generate.go, cmd/generate_test.go, cmd/golden/multi_accounts_vpc_route53_tgw.yaml, test_examples/multi_accounts_vpc_route53_tgw/network-account/eu-west-1/network/env.hcl, test_examples/multi_accounts_vpc_route53_tgw/network-account/eu-west-1/network/transit-gateway/terragrunt.hcl, test_examples/multi_accounts_vpc_route53_tgw/prod/eu-west-1/_global/env.hcl, test_examples/multi_accounts_vpc_route53_tgw/prod/eu-west-1/_global/route53/test-zone/terragrunt.hcl, test_examples/multi_accounts_vpc_route53_tgw/prod/eu-west-1/env-a/env.hcl, test_examples/multi_accounts_vpc_route53_tgw/prod/eu-west-1/env-a/network/vpc/terragrunt.hcl, test_examples/multi_accounts_vpc_route53_tgw/terragrunt.hcl
- _[none]_
- Improvement: In order to fix the issue with cascading dependencies this adds extra checks to handle both the case that a dependency uses an absolute path or a relative one.
- Improvement: Also converts relative dependencies to absolute to avoid duplicates and re-converts the dependencies to a relative before the configuration file is generated.
- Fix issue with parsing for a cascading dependencies case
Creates new terragrunt options with the dependency path in order to be able to parse successfully the cascading dependencies.
- _[none]_
- _[none]_
=> Fix issue with parsing for a cascading dependencies case, Fix Duplicated dependencies, Handle Relative/Absolute Paths more gracefully

.circleci/config.yml, Makefile, README.md, main.go
also removes a deprecated CI job
=> bump version to 1.1.1

cmd/generate.go, cmd/generate_test.go, cmd/golden/filterInfraLiveNonProd.yaml, cmd/golden/filterInfraLiveProd.yaml
- runatlantis/atlantis#1466
I was originally using the root flag for this but realized this caused
unintended issues with Atlantis and how the pattern matching is done.
This provides an additional flag "--filter" that is passed to
FindConfigFilesInPath() to only search a sub-path based on root.
- None
- All
=> feat: Add filter flag to allow generating configs for subset of folders

README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/filterGlobInfraLiveMySQL.yaml
- _[none]_
The current `--filter` implementation supports filtering by changing the base path. Consider the following layout and the requirement to run region1 modules in an atlantis instance hosted in region1 and region2 modules in an atlantis instance hosted in region2:
```
live
region1
modules-r1
region2
modules-r2
stage
region1
modules-r1
region2
modules-r2
```
The proposed extension of the `--filter` parameter for supporting glob expressions will allow for the generation of region specific configs:
`--filter "*/region1"` and `--filter "*/region2"`
The existing behaviour of the `--filter` parameter is not affected.
- _[none]_
- _[none]_
=> Add possibility to use glob expressions with --filter

Makefile, README.md, main.go
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/139
This makes compiled binaries statically linked, like they were at version 1.3.1 and lower.
Since version 1.4.1 (a.k.a moving to GitHub Actions), binaries started being dynamically linked, causing issues when running them on systems without proper libs installed (such as in a vanilla alpine Docker image).
I've compiled binaries with this code and they're available on https://github.com/gmpify/terragrunt-atlantis-config/releases/tag/v1.5.1; checking linux amd64:
```
$ file terragrunt-atlantis-config_1.5.1_linux_amd64
terragrunt-atlantis-config_1.5.1_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ETb7DcNyniNFkCi44IA2/iwvjiNliFGxrOJzQgHLP/Aim_1kHlIp5viEyZprY1/J8ZfmICRWG-rVD_ …
```
=> Make Github Actions compile statically linked binaries

cmd/golden/local_tf_module.yaml, cmd/parse_tf.go
Not sorting the output makes the output non-deterministic
=> Sort deep tf dependencies to make outputs consistent

cmd/generate.go, cmd/generate_test.go, cmd/golden/envhcl_allchilds.yaml, cmd/golden/envhcl_externalchilds.yaml, go.mod, test_examples/remote_module_source_bitbucket/terragrunt.hcl, test_examples/remote_module_source_gcs/terragrunt.hcl, test_examples/remote_module_source_git_https/terragrunt.hcl, test_examples/remote_module_source_git_scp_like/terragrunt.hcl, test_examples/remote_module_source_git_ssh/terragrunt.hcl, test_examples/remote_module_source_github_https/terragrunt.hcl, test_examples/remote_module_source_github_ssh/terragrunt.hcl, test_examples/remote_module_source_http/terragrunt.hcl, test_examples/remote_module_source_https/terragrunt.hcl, test_examples/remote_module_source_mercurial/terragrunt.hcl, test_examples/remote_module_source_s3/terragrunt.hcl, test_examples/remote_module_source_terraform_registry/terragrunt.hcl
- #172 
Refactor the remote module source path check to encompass all possible types. Use [go-getter](https://github.com/hashicorp/go-getter) to detect the source path, which normalizes the string into a format that can be checked by regex to cover any remote protocol prefix. This helps ensure we support the same source methods that Terraform (and by extension, Terragrunt) do.
Expand the test suite to cover all source methods as documented in the [Terraform docs](https://www.terraform.io/docs/language/modules/sources.html).
- _[none]_
- _[none]_
=> Check for all possible remote source methods

cmd/generate.go, cmd/generate_test.go, cmd/golden/envhcl_allchilds.yaml, cmd/golden/envhcl_externalchilds.yaml, cmd/golden/withOriginalDir.yaml, test_examples/with_original_dir/child/terragrunt.hcl, test_examples/with_original_dir/common/terragrunt.hcl, test_examples/with_original_dir/dependency/terragrunt.hcl, test_examples/with_original_dir/terragrunt.hcl
- #178 
This is the same functional code as #178 but rebased against current master and with tests added. This was based on the original PR code, so attributions should remain. I ran into a need for this function and found that PR just needing tests, hopefully this helps get this merged. 
One observation is that in the pattern of using a "common" folder (my use case) the common folder is not automatically pulled in as a dependency. A workaround is to set `extra_atlantis_dependencies` in the common `.hcl` file like this: 
```hcl
locals {
extra_atlantis_dependencies = [
"${get_parent_terragrunt_dir()}/terragrunt.hcl"
]
}
``` 
This can be seen in `test_examples/with_original_dir/common/terragrunt.hcl`. It may be something specific to how I am using this function, but wanted to call it out.
- …
=> feat: support get_original_terragrunt_dir

Makefile, README.md, go.mod, go.sum, main.go
This fixes issues where child terragrunt modules would have `include.root.inputs....` in dependency blocks.
With older terragrunt version dependency block parser wasn't able to resolve these fields from includes, resulting in `null` errors.
=> Bump terragrunt version to v0.35.16

Makefile, README.md, go.mod, go.sum, main.go
Bump of Terragrunt version to v0.36.1 to support new functions:
* error_hook 
#199 
- _[none]_
- _[none]_
=> Bump terragrunt version to 0.36.1

Makefile, README.md, cmd/generate.go, cmd/generate_test.go, cmd/golden/oldProjectsPreserved.yaml, main.go
- Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/152
Supports incremental builds by adding a new flag `--preserve-projects`, defaulting to false, that keeps old `atlantis.yaml` projects when writing out new ones
=> Support incremental builds

Makefile, README.md, go.mod, go.sum, main.go
- _#214_
Bump to the terragrunt version 0.36.6 in order to support the newly introduced dependency block attribute.
- _[none]_
- _[none]_
=> bump terragrunt version to 0.36.6

README.md
- _[none]_
`go get` is no longer supported outside a module.
- _[none]_
- _[none]_
=> Use `go install` in the `README`

README.md, cmd/config.go, cmd/generate.go, cmd/generate_test.go, cmd/golden/withExecutionOrderGroups.yaml
- #231
- https://github.com/runatlantis/atlantis/pull/2178
Added flag to compute execution_order_groups.
Currently, not supported extra dependencies in dockerignore notation. (like `**/terragrunt.hcl`)
To support everything need importing PatternMatcher from docker/fileutils pkg. I'm not sure this is needed.
- _[none]_
- _[none]_
=> feat: support execution_order_group

cmd/generate.go
- https://github.com/transcend-io/terragrunt-atlantis-config/issues/208
When using  `--preserve-projects` and `--filter` options together, replace existing block instead of duplicating it
Without this one has to resort to a workaround, such as using `python-yq` to remove the existing stanza from atlantis.yaml before partial generation.  Here are some performance measurements, showing a substantial improvement.
The measurements are for providing --filter with a single path, therefor generating/updating a single atlantis.yaml block.
1.	Old version with yq remove workaround 
21.53s user 1.41s system 91% cpu 25.040 total
2.	New version with yq remove workaround 
22.74s user 1.59s system 92% cpu 26.190 total
3.	New version without workaround 
**2.57s user 1.12s system 70% cpu 5.244 total**
- …
=> When using --preserve-projects and --filter options together, replace existing block instead of duplicating it

cmd/golden/envhcl_allchilds.yaml, cmd/golden/envhcl_externalchilds.yaml, cmd/parse_hcl.go, test_examples/hcl_json/json_expanded/terragrunt.hcl.json, test_examples/hcl_json/terragrunt.hcl
- [Issue#244](https://github.com/transcend-io/terragrunt-atlantis-config/issues/244)
- [Issue#243](https://github.com/transcend-io/terragrunt-atlantis-config/issues/243)
- [Terragrunt Issue#1951](https://github.com/gruntwork-io/terragrunt/issues/1951)
- Workaround to support `.hcl.json` files. 
- Added test cases with .hcl.json` files. 
- Issue: Repositories with `.hcl.json` files throw following error: 
```file_name.hcl.json:1,1-2: Argument or block definition required; An argument or block definition is required here.```
- Fix: Skip calling [updateBareIncludeBlock](https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/parse_hcl.go#L74) function for `.hcl.json` file formats, which in-turn skips usage of hclWrite library for hcl objects generated from `.hcl.json` …
=> fix: parsing json files

.github/workflows/container-build.yml, .github/workflows/contributors.yml, .github/workflows/release.yml, .github/workflows/run_tests.yml, Dockerfile, Makefile
I'm glad to see this project being revived!
I've been maintaining a fork used internally by our company and here are some CI fixes and improvements that might benefit the upstream project.
The most backward-incompatible change is probably around the build workflows, removing goxc which is no longer maintained, and changing the build artifact names and checksums (easier to remote copy the binaries directly instead of having to unzip files). I'm happy to discuss further some of these changes of course.
=> CI improvements

cmd/config.go, cmd/generate.go, cmd/generate_test.go
Replacing deprecated `ioutil` calls with the respective `os` counterparts.
Depends on #307.
=> Replace deprecated ioutil calls

.gitignore, Makefile, README.md, cmd/generate.go, main.go
- #300 
* ~~Fix env var parsing bug~~
* Add personal vscode workspace file to gitignore
* Update readme
=> Fix windows test failures

cmd/generate.go, cmd/generate_test.go, cmd/golden/filterInfraLiveProdAndNonProd.yaml
Update the type of the --filter flag so multiple paths or glob expressions can be passed as a comma-separated list.
This work was done by @rsinnet in https://github.com/transcend-io/terragrunt-atlantis-config/pull/264. I am just creating a PR with the rebased branch as @Almenon requested.
Update the type of the --filter flag so multiple paths or glob expressions can be passed as a comma-separated list.
- _[none]_
- _[none]_
=> Allow multiple paths with --filter flag

README.md, cmd/config.go, cmd/generate.go, cmd/generate_test.go, cmd/golden/withDependsOn.yaml, cmd/golden/withExecutionOrderGroups.yaml, cmd/golden/withExecutionOrderGroupsAndDependsOn.yaml, main.go, out
- #296 
- #319 
Adds functionality for `depends_on`
Fixes bug where the base execution_group (0) was not explicitly given.
- _[none]_
- _[none]_
=> add depends_on; fix execution_order_group 0.

cmd/generate.go
- #259 
A terragrunt file that uses `get_env("SOME_ENV_VAR")` and is a dependency to another one will get an error saying the env var does not exist. It works on files that are not a dependency.
This happens because the `getDependencies` function does not supply the environment variables to its recursive calls in this case.
- _[none]_
- _[none]_
=> fix: missing environment variables in dependencies

Makefile, README.md, main.go
I'll push a `v1.19.0` tag to master once this is merged in to trigger the CI. Hopefully I have permission to do that, it's been a while since the last release.
This release contains https://github.com/transcend-io/terragrunt-atlantis-config/pull/350 and some other misc changes
=> 1.19 release

cmd/generate_test.go, cmd/parse_locals.go, test_examples_errors/extra_dependency_error/child/terragrunt.hcl, test_examples_errors/extra_dependency_error/config.hcl
- #266 
This PR aims to improve the error message thrown when there's an invalid extra dependency declared. Since this problem made me lose a couple of minutes last week, I decided that we can show a proper message for when there's an invalid filepath set on the `extra_atlantis_dependencies` array.
For the example I'm adding on the test cases, the message before this PR was this:
```
panic: not a string
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:26 +0x64
golang.org/x/sync/singleflight.newPanicError({0x103183aa0, 0x103420890})
/Users/brunoferreira/go/pkg/mod/golang.org/x/sync@v0.4.0/singleflight/singleflight.go:44 +0x24
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
/Users/brunoferreira/go/pkg/mod/golang.org/x/sync@v0.4.0/singleflight/singleflight.go:193 +0x40 …
```
=> feat: improve error message for invalid extra atlantis dependencies

go.mod, go.sum
SOPS decryption via AWS EKS Pod Identity.
```
Error: /hello/secret/main.hcl:17,45-54: Unsupported attribute; This object does not have an attribute named "username"., and 3 other diagnostic(s)
```
OpenTofu, Terraform, and Terragrunt already use an AWS SDK version that supports AWS EKS Pod Identity.
This PR updates the aws-sdk-go version in terragrunt-atlantis-config to v1.47.11, which is the minimum required version for supporting AWS EKS Pod Identity. 
Ref https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11
This update resolves the SOPS decryption issue mentioned above.
- _[none]_
- _[none]_
=> feat: support AWS EKS Pod Identity
