README.md
cmd/generate.go

Another pr to add one more option, thanks and tested locally.

Add option to specify workflow name

---

.circleci/config.yml
cmd/generate.go
cmd/generate_test.go

Add support for Windows paths, and added tests on Windows executors
Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/19

Support Windows paths

---

Makefile
cmd/generate.go
cmd/generate_test.go
cmd/golden/invalid_parent_module.yaml
cmd/parse_hcl.go
go.mod
main.go
test_examples/invalid_parent_module/child/account.hcl
test_examples/invalid_parent_module/child/deep/terragrunt.hcl
test_examples/invalid_parent_module/child/env.hcl
test_examples/invalid_parent_module/child/region.hcl
test_examples/invalid_parent_module/terragrunt.hcl
test_examples/with_parent/terragrunt.hcl

Fixes https://github.com/transcend-io/terragrunt-atlantis-config/issues/35

Fix bug with --ignore-parent-terragrunt

---

Makefile
README.md
cmd/generate.go
cmd/generate_test.go
cmd/golden/different_workflow_names.yaml
cmd/parse_locals.go
main.go
test_examples/different_workflow_names/defaultWorkflow/terragrunt.hcl
test_examples/different_workflow_names/workflowA/terragrunt.hcl
test_examples/different_workflow_names/workflowB/terragrunt.hcl

Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/39

Allow setting custom workflows per project

---

.circleci/config.yml
README.md

Added official support for golang 1.15

Added testing for golang 1.15

---

Makefile
README.md
cmd/generate.go
cmd/generate_test.go
main.go

Release 0.7.0 adds support for parallel runs of atlantis

Cleanup for release 0.7.0

---

.goxc.json
Makefile
main.go

- _[none]_
- Support & Enable Multiple Platform Cross-Compilation of binaries & archives
- Corresponding Makefile Targets for the above
- Added Phony Targets in Makefile
- Drop Hardcoded Version from code
- _[none]_
- _[none]_

Support & Enable Cross Compilation of the Project for multiple Platforms & Other Optimizations

---

cmd/parse_locals.go

Sometimes files, especially parent files, are parsed numerous times. This quick change makes it so that that is not the case.

Add in cache for parsing local values

---

Makefile
README.md

Added documentation for the 0.9.0 release

Bump version to 0.9.0, added docs

---

Makefile
README.md
cmd/generate.go
cmd/generate_test.go
cmd/golden/extraArguments.yaml
main.go
test_examples/extra_arguments/child/terragrunt.hcl
test_examples/extra_arguments/terragrunt.hcl

- Fixes https://github.com/transcend-io/terragrunt-atlantis-config/issues/60
Handle extra_arguments variable files automatically

Handle extra_arguments variable files

---

Makefile
README.md
main.go

bump version to 0.9.3

---

Makefile
README.md
cmd/generate.go
main.go
test_examples/parent_with_extra_deps/parent/terragrunt.hcl

- https://github.com/transcend-io/terragrunt-atlantis-config/issues/60
Ignores dependencies that are the empty string

Ignore empty string dependencies

---

README.md

Fix the broken link to Atlantis in README.md

---

Makefile
README.md
main.go

Bumps minor version for release

bump minor version

---

README.md

- Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/86
Updates documentation for how to use this tool in a plug and play style, with no config needed to be committed to your repository

Update docs for plug and play usage

---

Makefile
README.md
main.go

version was left at 0.13.0 before the v1.0.0 release

bump version number to v1.0.1

---

README.md

Add stargazers to README

---

.github/workflows/release.yml
Makefile

- _[none]_
TODO
- _[none]_
- _[none]_

Fix release CI job

---

Makefile
README.md
main.go

- _[none]_
TODO
- _[none]_
- _[none]_

bump version to 1.5.0

---

Makefile
README.md
main.go

bump version to 1.6.0

---

cmd/generate.go
cmd/generate_test.go

- #145 
This PR provides consistent ordering of projects with parallel execution performing a sort by Dir.
- _[none]_
- _[none]_

Consistent ordering of projects with parallel execution

---

cmd/generate.go
cmd/generate_test.go
cmd/golden/local_tf_module.yaml
cmd/parse_tf.go
go.mod
go.sum
test_examples/local_tf_module_source/terraform-another-module/main.tf
test_examples/local_tf_module_source/terraform-module/main.tf
test_examples/local_tf_module_source/terraform-module/nested-module/main.tf
test_examples/local_tf_module_source/terraform/main.tf
test_examples/local_tf_module_source/terraform/terragrunt.hcl
test_examples/local_tf_module_source/terragrunt.hcl

- _[none]_
this changes not related to terragrunt, but it will help if we still using ``.tf` and it scan the local module
- _[none]_
- _[none]_

add dependency from terraform module source

---

cmd/golden/local_tf_module.yaml
cmd/parse_tf.go

Reverts transcend-io/terragrunt-atlantis-config#158

Revert "Sort deep tf dependencies to make outputs consistent"

---

Makefile
README.md
main.go

- _[none]_
TODO
- _[none]_
- _[none]_

bump version to 1.12.0

---

.github/workflows/release.yml

- _[none]_
Similar to #218.
- _[none]_
- _[none]_

Fix the release action - use `go install`

---

.github/workflows/release.yml

- #331 
the new checksum action is broken, so reverting back to original code
- _[none]_
- _[none]_

revert checksum changes

---

Makefile
README.md
main.go

PR for the release 1.20, as requested by @Almenon.

release 1.20
